{ pkgs, ... }:

{
  home.packages = [
    pkgs.a2ps
    pkgs.acpilight
    pkgs.antiword
    pkgs.arandr
    pkgs.bind
    pkgs.binutils
    pkgs.blueman
    pkgs.bluez
    pkgs.bluez-tools
    pkgs.cachix
    pkgs.cheese
    pkgs.ctags
    pkgs.elinks
    pkgs.evince
    pkgs.feh
    pkgs.ffmpeg
    pkgs.ffmpegthumbnailer
    pkgs.file
    pkgs.firefox
    pkgs.gimp
    pkgs.git
    pkgs.gnupg
    pkgs.gvfs
    pkgs.hamster
    pkgs.haskellPackages.xmobar
    pkgs.ibm-plex
    pkgs.inkscape
    pkgs.ispell
    pkgs.killall
    pkgs.libreoffice-fresh
    pkgs.lsof
    pkgs.noto-fonts-color-emoji
    pkgs.pandoc
    pkgs.parallel
    pkgs.pass
    pkgs.pavucontrol
    pkgs.pinentry-gnome3
    pkgs.poppler-utils
    pkgs.powertop
    pkgs.silver-searcher
    pkgs.sshpass
    pkgs.tmux
    pkgs.unzip
    pkgs.urlscan
    pkgs.usbutils
    pkgs.wget
    pkgs.xfce.thunar
    pkgs.xfce.thunar-volman
    pkgs.xfce.tumbler # needed for thumbnails
    pkgs.xlockmore
    pkgs.xss-lock
  ];
}
