username: ENC[AES256_GCM,data:JmbE3PFXMuday9uSsyiI,iv:nr0WI8k4NQP5+OqTGrYmfc9CwrcMGe3ZDluRZV/8ovY=,tag:S8hQInsloFUSdxj3QLQFdQ==,type:str]
password: ENC[AES256_GCM,data:G8IviuIFB9ytPPh2qgZyvA==,iv:5x+yITSJbCQ71UVr2Vazq/NFFDey9cv49s8wtRoB5sc=,tag:vvYAHzkpl08cuZ1U3AGZ9A==,type:str]
bookorbit_jwt_secret: ENC[AES256_GCM,data:T7wIUMKKOvmnSMdNJlbU6Hpy1m7WTU5pb4ifHdp1Oo6fwHcxWoKeDa4XKb8e55mIqbsvJnguAtMAb+T1tYmJ2g==,iv:cfbg94AeTo5vLC1rwVMxfODLAfSdAbDP6JsynWYhz40=,tag:3XuWUnz6IUUNCBrbTSw8RA==,type:str]
bookorbit_setup_bootstrap_token: ENC[AES256_GCM,data:0oBP0j9khl9vqDXQloNQFF/IWUdUiWZGCxoG2Hg/o8hhkYdLIZFUGPCTmnu5N/WvMOqEH88enwv68PjHjekSRQ==,iv:5B7041Q+U/1GAMtWyWZpCoyPrb2grRIUGVyiIryt+Kc=,tag:dAJQ9QQag45Oq5dDbWzOqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaW9lVW40V1hWeU5YS0s2
            aElDMmRnQWJ1L0ZsSHIwNXhSL1BkQVRNZVJzCnNrNWgzclZMclRVVkRrOVRVQjZH
            MmhXeGxqRU5hSUJKZ2NmU1NuczFmR0EKLS0tIHBSWkFnbGJsNkxMcFZGODFvdDli
            RXZxTndROVVYYmtxalo0bGR6SjI3WlkKmhJ4SG5AUCUrstbvGQYGmH+XKLjel6/y
            I0WTmx+bpR/mdmA13eVJSZzYjO5fO/G8CGFil5NO6IJFGIzE9hcNNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qpulahpfmm7unh2ajlyaza3p0k4rxpuyl38le93vj2mtzm7j39tqan8qwm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUFowUW1Wd3JpT25WNXdJ
            NVVNMzFWdktCQlV5bEkxWlZPd0JXVGduZnh3Cmg0WDVBcDAxZUxpc0VyT1dJbG1m
            cFR4OEZxaVc5MjJxbTJJZUdmRHhONHcKLS0tIGxyUjE2di9hWWp1dE9peVh4TDYw
            L0lFekhONWhYL1JKZGsvcmFFeXVLYjQKwgn+owle9gyE+qqpMNCefMTILPljflWy
            MWdAnFqwqleeO1y2IuDIqEN5uVdTMtSEYhOII/AQ6wlaXLHQoekF3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s8njlq8g2mfrjde7dpkmdy0a47d4weuckr5qpc0qf0zlschkwdzqa8f9p8
    lastmodified: "2026-09-23T05:49:28Z"
    mac: ENC[AES256_GCM,data:ZM93OyestoNtP3DWHQwav2imoIQ6WVVykc0HDolaOVSjB3OGQn7nyMfBS982y8b1lFk0IRW5pX2XQmS5m1OVmQSF/UzNTN8qBwLrFEPq5GRzgLGLJq0Bg9U5gxC1lFIVLiNVLUFPaquoZHlPto53Bt/xBTH90iOg/BJDJrFQNcU=,iv:qL7E03FvudvimxLGP+mgM96eVkmUcMQqZ/x5JBhzp+w=,tag:zM/efZMNjYXJKOxLZ83a2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
