username: ENC[AES256_GCM,data:JmbE3PFXMuday9uSsyiI,iv:nr0WI8k4NQP5+OqTGrYmfc9CwrcMGe3ZDluRZV/8ovY=,tag:S8hQInsloFUSdxj3QLQFdQ==,type:str]
password: ENC[AES256_GCM,data:G8IviuIFB9ytPPh2qgZyvA==,iv:5x+yITSJbCQ71UVr2Vazq/NFFDey9cv49s8wtRoB5sc=,tag:vvYAHzkpl08cuZ1U3AGZ9A==,type:str]
sops:
    age:
        - recipient: age1qpulahpfmm7unh2ajlyaza3p0k4rxpuyl38le93vj2mtzm7j39tqan8qwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaW9lVW40V1hWeU5YS0s2
            aElDMmRnQWJ1L0ZsSHIwNXhSL1BkQVRNZVJzCnNrNWgzclZMclRVVkRrOVRVQjZH
            MmhXeGxqRU5hSUJKZ2NmU1NuczFmR0EKLS0tIHBSWkFnbGJsNkxMcFZGODFvdDli
            RXZxTndROVVYYmtxalo0bGR6SjI3WlkKmhJ4SG5AUCUrstbvGQYGmH+XKLjel6/y
            I0WTmx+bpR/mdmA13eVJSZzYjO5fO/G8CGFil5NO6IJFGIzE9hcNNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s8njlq8g2mfrjde7dpkmdy0a47d4weuckr5qpc0qf0zlschkwdzqa8f9p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUFowUW1Wd3JpT25WNXdJ
            NVVNMzFWdktCQlV5bEkxWlZPd0JXVGduZnh3Cmg0WDVBcDAxZUxpc0VyT1dJbG1m
            cFR4OEZxaVc5MjJxbTJJZUdmRHhONHcKLS0tIGxyUjE2di9hWWp1dE9peVh4TDYw
            L0lFekhONWhYL1JKZGsvcmFFeXVLYjQKwgn+owle9gyE+qqpMNCefMTILPljflWy
            MWdAnFqwqleeO1y2IuDIqEN5uVdTMtSEYhOII/AQ6wlaXLHQoekF3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T08:29:51Z"
    mac: ENC[AES256_GCM,data:1e2TwzBkjlNQvEpPDAOVrshKI6dVxEloSzDr5gC+KtPPFk7eRFQnWq4BYJGfuVrrO94MjHs3Tu0aNk1AgHYuiG9gD6W/GUHIlXgwQoyKm85g8TxlHICnEToEB4UnhEfzLpBMozm2dqO7fOG1lIYN9tGfOnl8ynqcJLJkD+rkDqM=,iv:1+h25Ys7RIvwvEaQqo81u2jF5WhZCLIPfg8ZT8Ha7HM=,tag:lCuzVnUAuPdLA/dwUorfYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
