name: home-manager Build
on:
  - push
  - pull_request
jobs:
  linux:
    strategy:
      matrix:
        mapping:
          - { filename: home.nix, channel: nixos-unstable , home-manager-release: release-23.05 }
          - { filename: t14.nix, channel: nixos-unstable, home-manager-release: master }

    name: Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: "nixpkgs=channel:${{ matrix.mapping.channel }}"

      - name: Install home-manager channel
        run: |
          nix-channel --add https://github.com/nix-community/home-manager/archive/${{ matrix.mapping.home-manager-release }}.tar.gz home-manager
          nix-channel --update

      - name: Link home.nix
        run: |
          CONFIGPATH=$HOME/.config/home-manager
          mkdir -p "${CONFIGPATH}"
          cd "${CONFIGPATH}" && ln -s $GITHUB_WORKSPACE/nixpkgs/${{ matrix.mapping.filename }} "${CONFIGPATH}"/home.nix

      - name: Create secrets.nix
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/nixpkgs/secrets.nix
          {
            mailhost = "mail.testing.example";
            realName = "Róman Joost";
            email = "user@example.example";
            zshtheme = "pygmalion";
          }
          EOF

      - name: Build
        shell: bash
        run: |
          nix-shell -I $HOME/.nix-defexpr/channels '<home-manager>' -A install
